/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(rpitx_sink.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(80a79e1ba79298acadda3544286be907)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <rpitx/rpitx_sink.h>
// pydoc.h is automatically generated in the build directory
#include <rpitx_sink_pydoc.h>

void bind_rpitx_sink(py::module& m)
{

    using rpitx_sink    = ::gr::rpitx::rpitx_sink;


    py::class_<rpitx_sink, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<rpitx_sink>>(m, "rpitx_sink", D(rpitx_sink))

        .def(py::init(&rpitx_sink::make),
           py::arg("samp_rate"),
           py::arg("carrier_freq"),
           D(rpitx_sink,make)
        )
        




        
        .def("set_freq",&rpitx_sink::set_freq,       
            py::arg("arg0"),
            D(rpitx_sink,set_freq)
        )

        ;




}








