/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-rpitx
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_RPITX_API_H
#define INCLUDED_RPITX_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_rpitx_EXPORTS
#define RPITX_API __GR_ATTR_EXPORT
#else
#define RPITX_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_RPITX_API_H */
